# CREW Platform Environment Configuration
# Copy this file to .env and update with your values

# Database
MONGO_URI=mongodb://localhost:27017/crew_platform

# Twitter/X OAuth (Required - Get from Twitter Developer Console)
TWITTER_CONSUMER_KEY=your_twitter_consumer_key_here
TWITTER_CONSUMER_SECRET=your_twitter_consumer_secret_here
TWITTER_CALLBACK_URL=http://localhost:5000/auth/x/callback

# Security Keys (Auto-generated by deploy.sh)
JWT_SECRET=your_jwt_secret_here
ENCRYPTION_KEY=your_encryption_key_here
SESSION_SECRET=your_session_secret_here

# Server Configuration
PORT=5000
FRONTEND_DOMAIN=http://localhost:5000
ALLOWED_ORIGINS=http://localhost:5000,http://localhost:3000,http://localhost:5500,http://127.0.0.1:5500
NODE_ENV=development

# Blockchain
SOLANA_RPC_URL=https://api.devnet.solana.com

# Logging
LOG_LEVEL=info

# Production Settings (uncomment for production)
# NODE_ENV=production
# MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/crew_platform
# TWITTER_CALLBACK_URL=https://yourdomain.com/auth/x/callback
# FRONTEND_DOMAIN=https://yourdomain.com
# ALLOWED_ORIGINS=https://yourdomain.com
# SOLANA_RPC_URL=https://api.mainnet-beta.solana.com